import {
  Sword,
  Map,
  Laugh,
  Theater,
  Sparkles,
  Ghost,
  Heart,
  Orbit,
  AlertTriangle,
  Search,
  BookOpen,
  Palette,
  Music,
  ShieldQuestion,
  Flag,
  Mountain,
  Trophy,
  Users,
  Landmark,
} from "lucide-react";

export const GENRES_DATA = [
  {
    id: 1,
    name: "Action",
    description:
      "Movies with intense physical activity, fights, and explosions.",
    icon: Sword,
    movieGenres: [],
  },
  {
    id: 2,
    name: "Adventure",
    description: "Exciting stories featuring exploration or journeys.",
    icon: Map,
    movieGenres: [],
  },
  {
    id: 3,
    name: "Comedy",
    description: "Movies designed to make the audience laugh.",
    icon: Laugh,
    movieGenres: [],
  },
  {
    id: 4,
    name: "Drama",
    description:
      "Emotionally charged stories with realistic characters and conflicts.",
    icon: Theater,
    movieGenres: [],
  },
  {
    id: 5,
    name: "Fantasy",
    description: "Stories set in magical worlds with supernatural elements.",
    icon: Sparkles,
    movieGenres: [],
  },
  {
    id: 6,
    name: "Horror",
    description: "Movies that evoke fear, suspense, and shock.",
    icon: Ghost,
    movieGenres: [],
  },
  {
    id: 7,
    name: "Romance",
    description: "Stories focused on love and relationships.",
    icon: Heart,
    movieGenres: [],
  },
  {
    id: 8,
    name: "Science Fiction",
    description: "Movies based on futuristic science, technology, or space.",
    icon: Orbit,
    movieGenres: [],
  },
  {
    id: 9,
    name: "Thriller",
    description: "Suspenseful movies with twists and psychological tension.",
    icon: AlertTriangle,
    movieGenres: [],
  },
  {
    id: 10,
    name: "Mystery",
    description: "Stories involving crime, puzzles, or secrets to be solved.",
    icon: Search,
    movieGenres: [],
  },
  {
    id: 11,
    name: "Documentary",
    description: "Non-fiction films that document real-life subjects.",
    icon: BookOpen,
    movieGenres: [],
  },
  {
    id: 12,
    name: "Animation",
    description: "Movies created with drawings, CGI, or stop-motion animation.",
    icon: Palette,
    movieGenres: [],
  },
  {
    id: 13,
    name: "Musical",
    description: "Films that feature characters singing and dancing.",
    icon: Music,
    movieGenres: [],
  },
  {
    id: 14,
    name: "Crime",
    description:
      "Movies centered around criminals, police, and investigations.",
    icon: ShieldQuestion,
    movieGenres: [],
  },
  {
    id: 15,
    name: "War",
    description: "Films depicting battles, soldiers, and the impact of war.",
    icon: Flag,
    movieGenres: [],
  },
  {
    id: 16,
    name: "Western",
    description: "Stories set in the American frontier, often with cowboys.",
    icon: Mountain,
    movieGenres: [],
  },
  {
    id: 17,
    name: "Biography",
    description: "Films that tell the true story of a person’s life.",
    icon: Users,
    movieGenres: [],
  },
  {
    id: 18,
    name: "Sports",
    description: "Movies centered on athletic competition and teamwork.",
    icon: Trophy,
    movieGenres: [],
  },
  {
    id: 19,
    name: "Family",
    description: "Movies suitable for all ages, often with moral lessons.",
    icon: Landmark,
    movieGenres: [],
  },
  {
    id: 20,
    name: "Historical",
    description: "Films set in or inspired by real historical events.",
    icon: Landmark,
    movieGenres: [],
  },
];
