import type { Metadata } from "next";
import { Geist_Mono, Montserrat } from "next/font/google";
// @ts-ignore
import "./globals.css";
import { AppHeader } from "~/components/layouts/header";
import { Toaster } from "~/components/ui/sonner";
import { AllProviders } from "~/providers";

const geistSans = Montserrat({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Pop Corner",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geistSans.className}`}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased dark`}
      >
        <AllProviders>
          <AppHeader />
        </AllProviders>
        <Toaster />
        {children}
      </body>
    </html>
  );
}
